name: Java Tomcat Deployment

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java
        run: java -version

      - name: List Files
        run: ls -R

      - name: Build Maven Project
        run: mvn clean package -f MyWebApp/pom.xml

      - name: Verify WAR
        run: ls MyWebApp/target/

      - name: Deploy to Tomcat
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
          -T MyWebApp/target/*.war \
          "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/MyWebApp&update=true"

      - name: Deployment Status
        run: echo "Deployment Successful 🚀"
