name: Java Tomcat Deployment

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Verify Java
      - name: Verify Java
        run: java -version

      # Verify Maven
      - name: Verify Maven
        run: mvn -version

      # Show Repository Files
      - name: Show Repository Structure
        run: ls -R

      # Build Project
      - name: Build WAR File
        run: mvn clean package

      # Verify Generated WAR
      - name: Verify WAR File
        run: ls target/

      # Deploy WAR to Tomcat
      - name: Deploy to Tomcat
        run: |
          curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
          -T target/*.war \
          "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/MyWebApp&update=true"

      # Success Message
      - name: Deployment Success
        run: echo "Application Successfully Deployed 🚀"
